#!/usr/bin/env ruby

require 'io/console'
require 'nokogiri'

def find_file name
  [__dir__, '/usr/share/jargon', '/usr/local/share/jargon']
    .map {|v| File.join v, name}.find {|v| File.readable? v }
end

def term_match pattern, glossentry
  glossentry.at_css('glossterm').text.downcase =~ pattern
end

def full_text_match pattern, glossentry
  [glossentry.at_css('glossterm').text,
   glossentry.at_css('glossdef').text].join("\n").downcase =~ pattern
end

def term_print glossentry, _dummy
  puts glossentry.at_css('glossterm').text
end

class Glossentry
  def initialize node, idx, opt
    @opt = opt
    @term = term_parse node
    raise "invalid glossentry: no <glossterm>" unless @term[:term]

    @id = 'ge_' + @term[:term].strip.gsub(/[^A-Za-z0-9_-]+/, '_') + "_#{idx}"

    @defs = node.css('glossdef').map do |d|
      glossentry_to_html d      # in-place
      d.name = 'div'
      d.add_class 'glossdef'
    end
  end

  def print
    puts ':' + @term[:term] + ': ' + [@term[:pronunciation], @term[:grammar]]
                                       .filter {|v| v}.join(', ')
    puts

    @defs.each do |d|
      html = d.to_html
      puts html_to_text(html, @opt[:word_wrap])
    end
    puts
  end

  def term_parse node
    {
      term: node.at_css('glossterm')&.text,
      pronunciation: node.at_css('abbrev [role="pronunciation"]')&.text,
      grammar: node.at_css('abbrev [role="grammar"]')&.text,
    }
  end
end

class GlossentryHTML < Glossentry
  def print
    puts "<div class='glossentry' id='#{@id}'>"

    builder = Nokogiri::HTML5::Builder.new do |h|
      h.div(class: 'glossterm') {
        h.span(@term[:term], class: 'glossterm__term')
        h.span(@term[:pronunciation], class: 'glossterm__pronunciation') if @term[:pronunciation]
        h.span(@term[:grammar], class: 'glossterm__grammar') if @term[:grammar]
      }
    end
    puts builder.doc.root.to_html
    puts

    @defs.each { |d| puts d.to_html }

    puts "</div>\n\n"
  end
end

def entry_print glossentry, idx, opt
  klass = opt[:mode_html] ? GlossentryHTML : Glossentry
  ge = klass.new glossentry, idx, opt
  ge.print
end



def glossterm_to_text node
  node.content = "{#{node.text}}"
  node.name = 'span'
  node.add_class 'glossterm_link'
end

def ulink_to_a node
  node.name = 'a'
  node['href'] = node['url']
  node.remove_attribute('url')
end

def mediaobject_to_img node
  imagedata = node.at_css('imagedata')
  desc = node.at_css('caption')&.text&.strip

  if imagedata
    div = Nokogiri::XML::Node.new("div", Nokogiri::XML::Document.new)
    if desc
      div.content = "(#{desc})"
      div.prepend_child "<br/>"
    end

    img = Nokogiri::XML::Node.new("img", div)
    img['src'] = node.at_css('imagedata')['fileref']
    div.prepend_child img

    node.swap(div)
  end
end

def citerefentry_to_text node
  title = node.at_css('refentrytitle')&.text
  section = node.at_css('manvolnum')&.text
  if title
    node.content = "#{title}(#{section})"
    node.name = 'span'
    node.add_class 'citerefentry'
  end
end

def xref_to_text node           # jarg-specifig
  node.content = "[#{node['linkend']}]"
  node.name = 'span'
end

def quote_to_text node
  node.content = "\"#{node.text}\""
  node.name = 'cite'
end

def glossentry_to_html glossentry
  {
    'informaltable'  => 'table',
    'tgroup'         => nil,    # unwrap (remove but keep children)
    'row'            => 'tr',
    'entry'          => 'td',

    'para'           => 'p',
    'programlisting' => 'pre',
    'screen'         => 'pre',
    'literallayout'  => 'pre',
    'emphasis'       => 'em',
    'ulink'          => :ulink_to_a,
    'glossterm'      => :glossterm_to_text,
    'mediaobject'    => :mediaobject_to_img,
    'citerefentry'   => :citerefentry_to_text,
    'xref'           => :xref_to_text,
    'quote'          => :quote_to_text,

    'itemizedlist'   => 'ul',
    'orderedlist'    => 'ol',
    'listitem'       => 'li',
  }.each do |from, to|
    glossentry.css(from).each do |node|
      if to
        if to.is_a?(Symbol)
          method(to).call(node) # transform in-place
        else
          node.name = to
        end
      else
        node.replace(node.children) # unwrap
      end
    end
  end
end

def html_to_text html, word_wrap
  IO.popen([
             'w3m', '-T', 'text/html', '-dump', '-I', 'UTF-8',
             '-O', 'UTF-8', '-cols', word_wrap.to_s,
             '-o', 'display_link_number=1', '-o', 'display_borders=1',
           ], 'w+') do |pipe|
    pipe.write html
    pipe.close_write
    pipe.read
  end
end



def main
  abort "Usage: jargon pattern [fim]\n
  f       search inside defs too
  i       print terms only
  mNUM    stop after NUM matches" if ARGV.length < 1

  pattern = Regexp.new(ARGV[0], 'i', timeout: 1) rescue abort("invalid pattern: #{$!}")

  opt = {
    mode_indices: ARGV[1] =~ /i/,
    mode_full_text: ARGV[1] =~ /f/,
    mode_html: ARGV[1] =~ /h/,
    limit: (ARGV[1] =~ /m([0-9]+)/ && $1.to_i) || Float::INFINITY,
    word_wrap: ENV['MANWIDTH']&.to_i
  }
  opt[:word_wrap] = 76 if opt[:word_wrap] <= 0
  cols = IO.console.winsize[1]
  opt[:word_wrap] = cols if cols < opt[:word_wrap]

  ENV['XML_CATALOG_FILES'] = find_file('jargon.catalog.xml')
  ENV['XML_DEBUG_CATALOG'] = '1' if $VERBOSE

  doc = Nokogiri::XML(File.read find_file('jargon.xml')) {|o| o.dtdload.noent }
  doc.errors.each { |error| puts "libxml2 error: #{error.message}" } if $VERBOSE

  grep = opt[:mode_full_text] ? :full_text_match : :term_match
  print = opt[:mode_indices] ? :term_print : :entry_print

  status = 1
  doc.css('glossentry').each_with_index do |glossentry, idx|
    if send(grep, pattern, glossentry)
      opt[:limit] -= 1
      send(print, glossentry, idx, opt)
      status = 0
      break if opt[:limit] == 0
    end
  end

  exit status
end

main unless defined?(Minitest) || defined?(Test)
