#!/usr/bin/env ruby

require 'nokogiri'

abort "Usage: jargon pattern [fi]\n
         f    search inside defs too
         i    print terms only" if ARGV.length < 1

def find_file name
  [__dir__, '/usr/share/jargon', '/usr/local/share/jargon']
    .map {|v| File.join v, name}.find {|v| File.readable? v }
end

$conf = {
  mode: {
    indices: ARGV[1] =~ /i/,
    full_text: ARGV[1] =~ /f/,
  },
  word_wrap: 76
}

$pattern = Regexp.new ARGV[0], 'i'

def term_match pattern, glossentry
  glossentry.at_css('glossterm').text.downcase =~ pattern
end

def full_text_match pattern, glossentry
  [glossentry.at_css('glossterm').text,
   glossentry.at_css('glossdef').text].join("\n").downcase =~ pattern
end

def term_print glossentry
  puts glossentry.at_css('glossterm').text
end

def entry_print glossentry
  pronunciation = glossentry.at_css('abbrev [role="pronunciation"]')&.text
  grammar = glossentry.at_css('abbrev [role="grammar"]')&.text
  puts ':' + glossentry.at_css('glossterm').text + ': ' +
       [pronunciation, grammar].filter {|v| v}.join(', ')
  puts

  glossentry.css('glossdef').each do |node|
    glossentry_to_html node     # in-place
    node.name = 'div'
    node.add_class 'glossdef'
    html = node.to_html
    p html if $VERBOSE
    puts html_to_text(html)
  end
  puts
end



def glossterm_to_text node
  node.content = "{#{node.text}}"
  node.name = 'span'
  node.add_class 'glossterm'
end

def ulink_to_a node
  node.name = 'a'
  node['href'] = node['url']
  node.remove_attribute('url')
end

def mediaobject_to_img node
  imagedata = node.at_css('imagedata')
  desc = node.at_css('caption')&.text&.strip

  if imagedata
    div = Nokogiri::XML::Node.new("div", node.parent)
    if desc
      div.content = "(#{desc})"
      div.prepend_child "<br/>"
    end

    img = Nokogiri::XML::Node.new("img", div)
    img['src'] = node.at_css('imagedata')['fileref']
    div.prepend_child img

    node.swap(div)
  end
end

def citerefentry_to_text node
  title = node.at_css('refentrytitle')&.text
  section = node.at_css('manvolnum')&.text
  if title
    node.content = "#{title}(#{section})"
    node.name = 'span'
    node.add_class 'citerefentry'
  end
end

def xref_to_text node           # jarg-specifig
  node.content = "[#{node['linkend']}]"
  node.name = 'span'
end

def glossentry_to_html glossentry
  {
    'informaltable'  => 'table',
    'tgroup'         => nil,      # unwrap (remove but keep children)
    'row'            => 'tr',
    'entry'          => 'td',

    'para'           => 'p',
    'programlisting' => 'pre',
    'screen'         => 'pre',
    'literallayout' => 'pre',
    'emphasis'       => 'i',
    'ulink'          => :ulink_to_a,
    'glossterm'      => :glossterm_to_text,
    'mediaobject'    => :mediaobject_to_img,
    'citerefentry'   => :citerefentry_to_text,
    'xref' => :xref_to_text,
    'quote' => 'cite',

    'itemizedlist'   => 'ul',
    'orderedlist'    => 'ol',
    'listitem'       => 'li',

  }.each do |from, to|
    glossentry.css(from).each do |node|
      if to
        if to.is_a?(Symbol)
          method(to).call(node) # transform in-place
        else
          node.name = to
        end
      else
        node.replace(node.children) # unwrap
      end
    end
  end
end

def html_to_text html
  IO.popen([
             'w3m', '-T', 'text/html', '-dump', '-I', 'UTF-8',
             '-O', 'UTF-8', '-cols', $conf[:word_wrap].to_s,
             '-o', 'display_link_number=1', '-o', 'display_borders=1',
           ], 'w+') do |pipe|
    pipe.write html
    pipe.close_write
    pipe.read
  end
end



# dnf install docbook-dtds
ENV['XML_CATALOG_FILES'] = find_file('jargon.catalog.xml')
ENV['XML_DEBUG_CATALOG'] = '1' if $VERBOSE

doc = Nokogiri::XML(File.read find_file('jargon.xml')) {|o| o.dtdload.noent }

if $VERBOSE
  doc.errors.each do |error|
    puts "libxml2 error: #{error.message}"
  end
end

grep = $conf[:mode][:full_text] ? :full_text_match : :term_match
print = $conf[:mode][:indices] ? :term_print : :entry_print

status = 1
doc.css('glossentry').each do |glossentry|
  if send(grep, $pattern, glossentry)
    send(print, glossentry)
    status = 0
  end
end

exit status
